version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - bringel2-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: bringel2
      DB_USERNAME: root
      DB_PASSWORD: Nhaca70x07@
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bringel2-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Nhaca70x07@
      MYSQL_DATABASE: bringel2
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - bringel2-net

networks:
  bringel2-net:
    driver: bridge
